### ISSUE TITLE
Decide whether the npm package is 'heka' or 'heka-node'

### ISSUE THREAD

**Issue by chilts** [mozilla-services/heka-node#19]
From what I can see, the heka-node package is the newest version and has been updated the most recently.

I suggest:

1) choosing one (presumably 'heka-node' since that's currently in `package.json`)
2) deprecating the other one, and by that I mean either putting a notice on it's npm page to point to the new one, and/or deprecating old versions of it using https://www.npmjs.org/doc/cli/npm-deprecate.html

I'm happy to do other updates to docs etc once we have decided which one to use. :)

**Comment by rafrombrc** [comment]
heka-node is definitely the one we want. We'll work on deprecating the older one.
